version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: node --version
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm run test

  analyze:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm audit

workflows:
  build_test_analyze_workflow:
    jobs: 
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
